### ISSUE TITLE
.toe hangs at 99% when I try to open it

### ISSUE THREAD

**Issue by llwt** [GregFinger/TD-isorot#1]
Any idea why? I've been trying to figure out how to do what you have in here for a while and am super stoked to dive into this.
<img width="413" alt="Annotation 2019-11-26 214131" src="https://user-images.githubusercontent.com/1036428/69696799-a1dce000-1095-11ea-9adf-b07ed7325e3b.png">

**Comment by GregFinger** [comment]
What happens when you try it in the latest stable build 2019.19930? I think it might be the Curve Editor tox not cooperating in the experimental build. I can explore that later.

**Comment by GregFinger** [comment]
Ya, i've narrowed down the bug to a Text SOP that is referencing a DAT with line breaks, which in the experimental build causes crashing. This should still work in stable build.

**Comment by llwt** [comment]
Thanks for the quick reply! I didn't realize I had pulled down the experimental build.

**Comment by llwt** [comment]
Working for me on 2019.20140!
